# Primeiros passos com Pandas

Para instalar o Pandas rode no terminal:

```
pip install pandas
```

para importar o pandas:

In [2]:
import pandas as pd

Os principais objetos Pandas são Series e DataFrames

## Series

Uma Series no Pandas é uma estrutura de dados unidimensional, parecida com uma coluna de uma planilha. Ela armazena uma sequência de valores (como números, textos ou datas) acompanhados de um índice, que identifica cada elemento. Esse índice pode ser automático (0, 1, 2...) ou personalizado. As Series são muito úteis para representar e manipular listas de dados com rótulos, permitindo fazer operações matemáticas, filtragens e análises de forma simples e eficiente.

Os principais métodos de uma Series:

| Método                   | Descrição                                                 |
| :----------------------- | :-------------------------------------------------------- |
| `head(n)`                | Mostra os primeiros *n* elementos da Series (padrão = 5). |
| `tail(n)`                | Mostra os últimos *n* elementos da Series.                |
| `unique()`               | Retorna os valores únicos da Series.                      |
| `value_counts()`         | Conta quantas vezes cada valor aparece.                   |
| `mean()`                 | Calcula a média dos valores numéricos.                    |
| `sum()`                  | Retorna a soma dos valores.                               |
| `max()` / `min()`        | Retorna o maior ou menor valor.                           |
| `sort_values()`          | Ordena os valores da Series.                              |
| `isnull()` / `notnull()` | Verifica se há valores nulos (NaN).                       |
| `apply(func)`            | Aplica uma função personalizada a cada elemento.          |

No exemplo abaixo vemos uma lista de 100 notas que foram transformadas em uma Series Pandas. Repare em como cada nota tem um índice quando exibimos o resultado

In [2]:
# Lista com 100 notas inteiras
notas = [ 1,  0,  6,  3,  6,  4,  4,  9,  5,  2,  4,  3,  9,  9,  9, 10,  9,
        8,  1, 10,  1,  9,  1,  4,  2,  6,  3,  5, 10,  0, 10,  6,  0,  7,
        7,  6,  7,  4,  4,  8,  9,  5,  5,  0, 10,  4,  3,  0,  2, 10,  1,
       10,  4,  7,  1,  7,  0,  7,  0,  3, 10,  6,  7,  0,  3,  6,  3,  7,
        3,  6,  8,  3,  6,  8,  6,  3,  9,  5,  0,  4,  9,  7,  0,  5,  7,
        8,  8,  3,  5,  9, 10,  5,  6,  4,  6,  0,  9,  6,  7,  4]
print('Tipo da variável: ',type(notas)) # Verifica o tipo original

# Transforma a lista em Series
notas = pd.Series(notas)
print('Tipo da variável: ',type(notas)) # Verifica o tipo após a mudança
print(notas) # Exibe a Series

Tipo da variável:  <class 'list'>
Tipo da variável:  <class 'pandas.core.series.Series'>
0     1
1     0
2     6
3     3
4     6
     ..
95    0
96    9
97    6
98    7
99    4
Length: 100, dtype: int64

Exibindo as 5 primeiras e últimas notas

In [3]:
# 5 primeiras notas
notas.head(5)

0    1
1    0
2    6
3    3
4    6
dtype: int64

In [4]:
# 5 últimas notas
notas.tail(5)

95    0
96    9
97    6
98    7
99    4
dtype: int64

Exibindo somente as notas "únicas" (sem repetições)

In [5]:
notas.sort_values().unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Exibindo a quantidade de ocorrências de cada nota

In [7]:
notas.value_counts()

6     13
0     11
3     11
9     11
4     11
7     11
10     9
5      8
1      6
8      6
2      3
Name: count, dtype: int64

Não deixe de testar os outros métodos

---

## DataFrames

Um DataFrame é a estrutura de dados bidimensional do Pandas, semelhante a uma tabela do Excel, com linhas e colunas. Cada coluna de um DataFrame é, na verdade, uma Series, o que permite trabalhar com diferentes tipos de dados (números, textos, datas, etc.) ao mesmo tempo. Essa estrutura é ideal para armazenar, organizar e analisar grandes conjuntos de dados, permitindo realizar operações como filtragem, agrupamento, cálculos estatísticos e muito mais de forma rápida e intuitiva.

Principais métodos de um DataFrame:

| Método                    | Descrição                                                        |
| :------------------------ | :--------------------------------------------------------------- |
| `head(n)`                 | Mostra as primeiras *n* linhas do DataFrame.                     |
| `info()`                  | Exibe informações sobre colunas, tipos de dados e valores nulos. |
| `describe()`              | Gera estatísticas descritivas (média, desvio padrão, etc.).      |
| `shape`                   | Retorna o número de linhas e colunas (tupla).                    |
| `columns`                 | Mostra os nomes das colunas.                                     |
| `dtypes`                  | Mostra o tipo de dado de cada coluna.                            |
| `loc[]`                   | Acessa linhas e colunas pelo nome.                               |
| `iloc[]`                  | Acessa linhas e colunas pela posição.                            |
| `drop()`                  | Remove colunas ou linhas.                                        |
| `groupby()`               | Agrupa os dados com base em uma ou mais colunas.                 |
| `sort_values()`           | Ordena os dados por uma coluna específica.                       |
| `fillna()`                | Substitui valores nulos (NaN) por outro valor.                   |
| `merge()`                 | Junta dois DataFrames (como em SQL JOIN).                        |
| `to_csv()` / `read_csv()` | Exporta ou importa dados em formato CSV.                         |

Geralmente o objeto DataFrame é criado automáticamente quando importamos um conjunto de dados usando pd.read_excel() ou qualquer função do tipo, por exemplo.

Mas neste momento vamos criar um DataFrame do zero para entender melhor como ele funciona

In [10]:
dados = {
    'nomes' : ['Joao', 'Maria', 'Fernanda', 'Pedro', 'Robson', 'Moacir', 'Alex', 'Lara'],
    'notas' : [8,  9,  5,  5, 10,  4,  3, 2]
    }


df = pd.DataFrame(dados)
df

      nomes  notas
0      Joao      8
1     Maria      9
2  Fernanda      5
3     Pedro      5
4    Robson     10
5    Moacir      4
6      Alex      3
7      Lara      2

Para selecionar apenas uma colunas funciona de maneira semelhante à acessar uma chave de um dicionário. Porém com o detalhe que o objeto retornado é uma Series.

In [11]:
# Selecionando apenas a coluna 'nomes'
df['nomes']

0        Joao
1       Maria
2    Fernanda
3       Pedro
4      Robson
5      Moacir
6        Alex
7        Lara
Name: nomes, dtype: object

In [ ]:
# selecionando apenas a coluna 'notas'
df['notas']

0     8
1     9
2     5
3     5
4    10
5     4
6     3
7     2
Name: notas, dtype: int64

Descobrindo a média de todas as notas:

In [ ]:
df['notas'].mean()

np.float64(5.75)

Para filtrar um registro:

In [ ]:
# Isso gera uma Series de True/False (Bool)
df['notas'] > 5 # Lista de Verdadeiros e Falsos

0     True
1     True
2    False
3    False
4     True
5    False
6    False
7    False
Name: notas, dtype: bool

Nós podemos transformar essa Series de volta em um Dataframe passando esta mesma linha de código no colchetes do DataFrame

In [ ]:
df[df['notas'] > 5] # Desta maneira podemos usar a lógica booleana para filtrar linhas em um DataFrame

    nomes  notas
0    Joao      8
1   Maria      9
4  Robson     10

## Analizando um pouco melhor o DataFrame

Com o DataFrame em mãos, podemos verificar algumas informações importantes sobre a quantidade de linhas e colunas, tipos de dados, tamanho em bytes ocupado na memória e etc utilizando o método **df.info()**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nomes   8 non-null      object
 1   notas   8 non-null      int64
dtypes: int64(1), object(1)
memory usage: 260.0+ bytes

---

Informações do DataFrame:
- Podemos ver o tipo da variável = 'pandas.core.frame.DataFrame'
- A quantidade de linhas do DataFrame (RangeIndex) = 8 entries, 0 to 7 (Significa que tem 8 linhas e o índice vai de 0 à 7)
- A quantidade de colunas (Data columns) = total 2 columns (Duas colunas)

Em seguida vemos informações sobre as colunas:
- O nome (Column) = informa em ordem o nome das colunas
- Non-Null Count = informa a quantidade de registros 'não vazios' naquela coluna
- Dtype = Informa o tipo de dados contidos naquela coluna (object significa que é uma coluna de strings)

Por últimos temos:
- dtypes = uma relação de todos os tipos de colunas
- memory usage = o espaço que o dataframe ocupa na memória ram enquanto o script python está sendo executado

# Exercícios

## 1 - Importe 'pandas' como pd

In [8]:
import pandas as pd

## 2 - Transforme o dicionário abaixo em um DataFrame e exiba a tabela Dataframe

In [7]:
funcionarios = {
    "nome": [
        "Ana Souza", "Bruno Lima", "Carla Ferreira", "Diego Santos", "Eduarda Nascimento",
        "Felipe Almeida", "Giovana Ramos", "Henrique Costa", "Isabela Araujo", "João Pereira",
        "Karina Oliveira", "Lucas Rodrigues", "Mariana Machado", "Nathan Silva", "Olívia Barbosa"
    ],
    "unidade": [
        2, 1, 3, 2, 1,
        3, 1, 2, 3, 1,
        2, 3, 1, 3, 2
    ],
    "escala_noturna": [
        False, True, False, True, False,
        True, False, True, False, True,
        False, True, False, True, False
    ],
    "vendas": [
        18754.32, 24321.89, 19876.45, 27543.22, 15789.66,
        29123.10, 22345.99, 26789.40, 19456.78, 28345.55,
        17654.12, 23876.99, 20543.70, 29654.88, 18321.44
    ]
}

In [16]:
df = pd.DataFrame(funcionarios)
df

                  nome  unidade  escala_noturna    vendas
0            Ana Souza        2           False  18754.32
1           Bruno Lima        1            True  24321.89
2       Carla Ferreira        3           False  19876.45
3         Diego Santos        2            True  27543.22
4   Eduarda Nascimento        1           False  15789.66
5       Felipe Almeida        3            True  29123.10
6        Giovana Ramos        1           False  22345.99
7       Henrique Costa        2            True  26789.40
8       Isabela Araujo        3           False  19456.78
9         João Pereira        1            True  28345.55
10     Karina Oliveira        2           False  17654.12
11     Lucas Rodrigues        3            True  23876.99
12     Mariana Machado        1           False  20543.70
13        Nathan Silva        3            True  29654.88
14      Olívia Barbosa        2           False  18321.44

In [ ]:
# Não rode essa linha de código para não perder o resultado de exemplo

                  nome  unidade  escala_noturna    vendas
0            Ana Souza        2           False  18754.32
1           Bruno Lima        1            True  24321.89
2       Carla Ferreira        3           False  19876.45
3         Diego Santos        2            True  27543.22
4   Eduarda Nascimento        1           False  15789.66
5       Felipe Almeida        3            True  29123.10
6        Giovana Ramos        1           False  22345.99
7       Henrique Costa        2            True  26789.40
8       Isabela Araujo        3           False  19456.78
9         João Pereira        1            True  28345.55
10     Karina Oliveira        2           False  17654.12
11     Lucas Rodrigues        3            True  23876.99
12     Mariana Machado        1           False  20543.70
13        Nathan Silva        3            True  29654.88
14      Olívia Barbosa        2           False  18321.44

## 3 - Exiba as informações de dimensões, linhas, colunas e tipos de dados do DataFrame

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nome            15 non-null     object
 1   unidade         15 non-null     int64
 2   escala_noturna  15 non-null     bool
 3   vendas          15 non-null     float64
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 507.0+ bytes

In [ ]:
# Não rode essa linha de código para não perder o resultado de exemplo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nome            15 non-null     object
 1   unidade         15 non-null     int64
 2   escala_noturna  15 non-null     bool
 3   vendas          15 non-null     float64
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 507.0+ bytes

## 4 - Quantos funcionários temos em cada unidade? dica: utilize o método value_counts()

In [33]:
df.value_counts(funcionarios['unidade'])

1    5
2    5
3    5
Name: count, dtype: int64

In [ ]:
# Não rode essa linha de código para não perder o resultado de exemplo

unidade
2    5
1    5
3    5
Name: count, dtype: int64

## 5 - Seguindo a mesma lógica do exercício anterior, quantos funcionários trabalham de noite ou de dia

In [34]:
df.value_counts(funcionarios['escala_noturna'])

False    8
True     7
Name: count, dtype: int64

In [ ]:
# Não rode essa linha de código para não perder o resultado de exemplo

escala_noturna
False    8
True     7
Name: count, dtype: int64

## 6 - Qual foi o total de vendas do funcionário chamado Henrique Costa? (utilize a filtragem para descobrir)

In [51]:
df = pd.DataFrame(funcionarios)
df[df["nome"] == "Henrique Costa"]

             nome  unidade  escala_noturna   vendas
7  Henrique Costa        2            True  26789.4

In [ ]:
# Não rode essa linha de código para não perder o resultado de exemplo

             nome  unidade  escala_noturna   vendas
7  Henrique Costa        2            True  26789.4

## 7 - Quais funcionários venderam menos do que R$20000 ?

In [55]:
df = pd.DataFrame(funcionarios)
df[df["vendas"] < 20000]

                  nome  unidade  escala_noturna    vendas
0            Ana Souza        2           False  18754.32
2       Carla Ferreira        3           False  19876.45
4   Eduarda Nascimento        1           False  15789.66
8       Isabela Araujo        3           False  19456.78
10     Karina Oliveira        2           False  17654.12
14      Olívia Barbosa        2           False  18321.44

In [ ]:
# Não rode essa linha de código para não perder o resultado de exemplo

                  nome  unidade  escala_noturna    vendas
0            Ana Souza        2           False  18754.32
2       Carla Ferreira        3           False  19876.45
4   Eduarda Nascimento        1           False  15789.66
8       Isabela Araujo        3           False  19456.78
10     Karina Oliveira        2           False  17654.12
14      Olívia Barbosa        2           False  18321.44

## 8 - (**BONUS**) O total de vendas é maior durante o dia ou noite? (Não se preocupe com o groupby por enquanto, apenas some as vendas para cada periodo)

In [66]:
df_noturno = df[df["escala_noturna"] == True]
vendas_nortuno = df_noturno["vendas"].sum()

df_diurno = df[df["escala_noturna"] == False]
vendas_diurno = df_diurno["vendas"].sum()

print(f"Vendas de noite: {vendas_nortuno:.2f}")
print(f"Vendas de dia: {vendas_diurno:.2f}")

Vendas de noite: 189655.03
Vendas de dia: 152742.46

In [ ]:
# Não rode essa linha de código para não perder o resultado de exemplo

Vendas de noite: R$189655.03
Vendas de dia: R$152742.46

In [71]:
carros = {
    "Fiat": {
        "modelos": [
            {"nome": "Fiat Argo 1.0 Flex", "valor": 72500},
            {"nome": "Fiat Cronos 1.3 Flex", "valor": 89200},
            {"nome": "Fiat Mobi Easy 1.0", "valor": 61800},
            {"nome": "Fiat Pulse Drive 1.0 Turbo", "valor": 112400},
            {"nome": "Fiat Toro Freedom 1.3 Turbo Flex", "valor": 156900}
        ]
    },
    "Renault": {
        "modelos": [
            {"nome": "Renault Kwid Zen 1.0 Flex", "valor": 68300},
            {"nome": "Renault Logan Expression 1.6 Flex", "valor": 92700},
            {"nome": "Renault Captur Iconic 1.3 Turbo Flex", "valor": 142800},
            {"nome": "Renault Duster Intense 1.6 CVT", "valor": 128600},
            {"nome": "Renault Oroch Outsider 1.3 Turbo Flex", "valor": 154200}
        ]
    },
    "Hyundai": {
        "modelos": [
            {"nome": "Hyundai HB20 Sense 1.0", "valor": 78400},
            {"nome": "Hyundai HB20S Comfort Plus 1.6", "valor": 96200},
            {"nome": "Hyundai Creta Action 1.6", "valor": 128900},
            {"nome": "Hyundai Creta Ultimate 2.0", "valor": 168500},
            {"nome": "Hyundai Tucson GLS 2.0 Flex", "valor": 152700}
        ]
    },
    "Chevrolet": {
        "modelos": [
            {"nome": "Chevrolet Onix LT 1.0", "valor": 77600},
            {"nome": "Chevrolet Onix Plus LT 1.0 Turbo", "valor": 94800},
            {"nome": "Chevrolet Tracker LT 1.0 Turbo", "valor": 132400},
            {"nome": "Chevrolet Spin Premier 1.8", "valor": 118900},
            {"nome": "Chevrolet S10 LTZ 2.8 Diesel", "valor": 236500}
        ]
    },
    "Toyota": {
        "modelos": [
            {"nome": "Toyota Corolla GLi 2.0 Flex", "valor": 152800},
            {"nome": "Toyota Corolla Cross XRE 2.0", "valor": 176400},
            {"nome": "Toyota Hilux SRV 2.8 Diesel", "valor": 268900},
            {"nome": "Toyota Yaris XS 1.5", "valor": 104500},
            {"nome": "Toyota SW4 SRX 2.8 Diesel", "valor": 342700}
        ]
    },
    "Honda": {
        "modelos": [
            {"nome": "Honda City EX 1.5", "valor": 118600},
            {"nome": "Honda City Hatchback Touring 1.5", "valor": 124900},
            {"nome": "Honda Civic Sport 2.0", "valor": 156800},
            {"nome": "Honda HR-V EXL 1.5 Turbo", "valor": 178400},
            {"nome": "Honda CR-V Touring 1.5 Turbo", "valor": 238900}
        ]
    },
    "Jeep": {
        "modelos": [
            {"nome": "Jeep Renegade Sport 1.3 Turbo", "valor": 132700},
            {"nome": "Jeep Compass Longitude 1.3 Turbo", "valor": 176900},
            {"nome": "Jeep Compass Trailhawk 2.0 Diesel", "valor": 228400},
            {"nome": "Jeep Commander Limited 2.0 Diesel", "valor": 268800},
            {"nome": "Jeep Wrangler Rubicon 2.0 Turbo", "valor": 356200}
        ]
    }
}

dados = []
for marca, info in carros.items():
    for modelo in info["modelos"]:
        dados.append({
            "marca": marca,
            "nome": modelo["nome"],
            "valor": modelo["valor"]
        })

In [72]:
df = pd.DataFrame(dados)
df

        marca                                   nome   valor
0        Fiat                     Fiat Argo 1.0 Flex   72500
1        Fiat                   Fiat Cronos 1.3 Flex   89200
2        Fiat                     Fiat Mobi Easy 1.0   61800
3        Fiat             Fiat Pulse Drive 1.0 Turbo  112400
4        Fiat       Fiat Toro Freedom 1.3 Turbo Flex  156900
5     Renault              Renault Kwid Zen 1.0 Flex   68300
6     Renault      Renault Logan Expression 1.6 Flex   92700
7     Renault   Renault Captur Iconic 1.3 Turbo Flex  142800
8     Renault         Renault Duster Intense 1.6 CVT  128600
9     Renault  Renault Oroch Outsider 1.3 Turbo Flex  154200
10    Hyundai                 Hyundai HB20 Sense 1.0   78400
11    Hyundai         Hyundai HB20S Comfort Plus 1.6   96200
12    Hyundai               Hyundai Creta Action 1.6  128900
13    Hyundai             Hyundai Creta Ultimate 2.0  168500
14    Hyundai            Hyundai Tucson GLS 2.0 Flex  152700
15  Chevrolet                  Chevrolet Onix LT 1.0   77600
16  Chevrolet       Chevrolet Onix Plus LT 1.0 Turbo   94800
17  Chevrolet         Chevrolet Tracker LT 1.0 Turbo  132400
18  Chevrolet             Chevrolet Spin Premier 1.8  118900
19  Chevrolet           Chevrolet S10 LTZ 2.8 Diesel  236500
20     Toyota            Toyota Corolla GLi 2.0 Flex  152800
21     Toyota           Toyota Corolla Cross XRE 2.0  176400
22     Toyota            Toyota Hilux SRV 2.8 Diesel  268900
23     Toyota                    Toyota Yaris XS 1.5  104500
24     Toyota              Toyota SW4 SRX 2.8 Diesel  342700
25      Honda                      Honda City EX 1.5  118600
26      Honda       Honda City Hatchback Touring 1.5  124900
27      Honda                  Honda Civic Sport 2.0  156800
28      Honda               Honda HR-V EXL 1.5 Turbo  178400
29      Honda           Honda CR-V Touring 1.5 Turbo  238900
30       Jeep          Jeep Renegade Sport 1.3 Turbo  132700
31       Jeep       Jeep Compass Longitude 1.3 Turbo  176900
32       Jeep      Jeep Compass Trailhawk 2.0 Diesel  228400
33       Jeep      Jeep Commander Limited 2.0 Diesel  268800
34       Jeep        Jeep Wrangler Rubicon 2.0 Turbo  356200

In [75]:
df = pd.DataFrame(dados)
df[df["valor"] > 50000]

        marca                                   nome   valor
0        Fiat                     Fiat Argo 1.0 Flex   72500
1        Fiat                   Fiat Cronos 1.3 Flex   89200
2        Fiat                     Fiat Mobi Easy 1.0   61800
3        Fiat             Fiat Pulse Drive 1.0 Turbo  112400
4        Fiat       Fiat Toro Freedom 1.3 Turbo Flex  156900
5     Renault              Renault Kwid Zen 1.0 Flex   68300
6     Renault      Renault Logan Expression 1.6 Flex   92700
7     Renault   Renault Captur Iconic 1.3 Turbo Flex  142800
8     Renault         Renault Duster Intense 1.6 CVT  128600
9     Renault  Renault Oroch Outsider 1.3 Turbo Flex  154200
10    Hyundai                 Hyundai HB20 Sense 1.0   78400
11    Hyundai         Hyundai HB20S Comfort Plus 1.6   96200
12    Hyundai               Hyundai Creta Action 1.6  128900
13    Hyundai             Hyundai Creta Ultimate 2.0  168500
14    Hyundai            Hyundai Tucson GLS 2.0 Flex  152700
15  Chevrolet                  Chevrolet Onix LT 1.0   77600
16  Chevrolet       Chevrolet Onix Plus LT 1.0 Turbo   94800
17  Chevrolet         Chevrolet Tracker LT 1.0 Turbo  132400
18  Chevrolet             Chevrolet Spin Premier 1.8  118900
19  Chevrolet           Chevrolet S10 LTZ 2.8 Diesel  236500
20     Toyota            Toyota Corolla GLi 2.0 Flex  152800
21     Toyota           Toyota Corolla Cross XRE 2.0  176400
22     Toyota            Toyota Hilux SRV 2.8 Diesel  268900
23     Toyota                    Toyota Yaris XS 1.5  104500
24     Toyota              Toyota SW4 SRX 2.8 Diesel  342700
25      Honda                      Honda City EX 1.5  118600
26      Honda       Honda City Hatchback Touring 1.5  124900
27      Honda                  Honda Civic Sport 2.0  156800
28      Honda               Honda HR-V EXL 1.5 Turbo  178400
29      Honda           Honda CR-V Touring 1.5 Turbo  238900
30       Jeep          Jeep Renegade Sport 1.3 Turbo  132700
31       Jeep       Jeep Compass Longitude 1.3 Turbo  176900
32       Jeep      Jeep Compass Trailhawk 2.0 Diesel  228400
33       Jeep      Jeep Commander Limited 2.0 Diesel  268800
34       Jeep        Jeep Wrangler Rubicon 2.0 Turbo  356200

In [76]:
df = pd.DataFrame(dados)
df[df["valor"] < 70000]

     marca                       nome  valor
2     Fiat         Fiat Mobi Easy 1.0  61800
5  Renault  Renault Kwid Zen 1.0 Flex  68300

In [77]:
df = pd.DataFrame(dados)
df[df["marca"] == "Fiat"]

  marca                              nome   valor
0  Fiat                Fiat Argo 1.0 Flex   72500
1  Fiat              Fiat Cronos 1.3 Flex   89200
2  Fiat                Fiat Mobi Easy 1.0   61800
3  Fiat        Fiat Pulse Drive 1.0 Turbo  112400
4  Fiat  Fiat Toro Freedom 1.3 Turbo Flex  156900

In [4]:
import pandas as pd

vencedores = [
    {"ano": 1956, "jogador": "Stanley Matthews", "pais": "Inglaterra"},
    {"ano": 1957, "jogador": "Alfredo Di Stéfano", "pais": "Argentina/Espanha"},
    {"ano": 1958, "jogador": "Raymond Kopa", "pais": "França"},
    {"ano": 1959, "jogador": "Alfredo Di Stéfano", "pais": "Argentina/Espanha"},
    {"ano": 1960, "jogador": "Luis Suárez Miramontes", "pais": "Espanha"},
    {"ano": 1961, "jogador": "Omar Sívori", "pais": "Argentina/Itália"},
    {"ano": 1962, "jogador": "Josef Masopust", "pais": "Tchecoslováquia"},
    {"ano": 1963, "jogador": "Lev Yashin", "pais": "URSS"},
    {"ano": 1964, "jogador": "Denis Law", "pais": "Escócia"},
    {"ano": 1965, "jogador": "Eusébio", "pais": "Portugal"},
    {"ano": 1966, "jogador": "Bobby Charlton", "pais": "Inglaterra"},
    {"ano": 1967, "jogador": "Flórián Albert", "pais": "Hungria"},
    {"ano": 1968, "jogador": "George Best", "pais": "Irlanda do Norte"},
    {"ano": 1969, "jogador": "Gianni Rivera", "pais": "Itália"},
    {"ano": 1970, "jogador": "Gerd Müller", "pais": "Alemanha"},
    {"ano": 1971, "jogador": "Johan Cruyff", "pais": "Holanda"},
    {"ano": 1972, "jogador": "Franz Beckenbauer", "pais": "Alemanha"},
    {"ano": 1973, "jogador": "Johan Cruyff", "pais": "Holanda"},
    {"ano": 1974, "jogador": "Johan Cruyff", "pais": "Holanda"},
    {"ano": 1975, "jogador": "Oleg Blokhin", "pais": "URSS"},
    {"ano": 1976, "jogador": "Franz Beckenbauer", "pais": "Alemanha"},
    {"ano": 1977, "jogador": "Allan Simonsen", "pais": "Dinamarca"},
    {"ano": 1978, "jogador": "Kevin Keegan", "pais": "Inglaterra"},
    {"ano": 1979, "jogador": "Kevin Keegan", "pais": "Inglaterra"},
    {"ano": 1980, "jogador": "Karl-Heinz Rummenigge", "pais": "Alemanha"},
    {"ano": 1981, "jogador": "Karl-Heinz Rummenigge", "pais": "Alemanha"},
    {"ano": 1982, "jogador": "Paolo Rossi", "pais": "Itália"},
    {"ano": 1983, "jogador": "Michel Platini", "pais": "França"},
    {"ano": 1984, "jogador": "Michel Platini", "pais": "França"},
    {"ano": 1985, "jogador": "Michel Platini", "pais": "França"},
    {"ano": 1986, "jogador": "Igor Belanov", "pais": "URSS"},
    {"ano": 1987, "jogador": "Ruud Gullit", "pais": "Holanda"},
    {"ano": 1988, "jogador": "Marco van Basten", "pais": "Holanda"},
    {"ano": 1989, "jogador": "Marco van Basten", "pais": "Holanda"},
    {"ano": 1990, "jogador": "Lothar Matthäus", "pais": "Alemanha"},
    {"ano": 1991, "jogador": "Jean-Pierre Papin", "pais": "França"},
    {"ano": 1992, "jogador": "Marco van Basten", "pais": "Holanda"},
    {"ano": 1993, "jogador": "Roberto Baggio", "pais": "Itália"},
    {"ano": 1994, "jogador": "Hristo Stoichkov", "pais": "Bulgária"},
    {"ano": 1995, "jogador": "George Weah", "pais": "Libéria"},
    {"ano": 1996, "jogador": "Matthias Sammer", "pais": "Alemanha"},
    {"ano": 1997, "jogador": "Ronaldo", "pais": "Brasil"},
    {"ano": 1998, "jogador": "Zinedine Zidane", "pais": "França"},
    {"ano": 1999, "jogador": "Rivaldo", "pais": "Brasil"},
    {"ano": 2000, "jogador": "Luís Figo", "pais": "Portugal"},
    {"ano": 2001, "jogador": "Michael Owen", "pais": "Inglaterra"},
    {"ano": 2002, "jogador": "Ronaldo", "pais": "Brasil"},
    {"ano": 2003, "jogador": "Pavel Nedvěd", "pais": "República Tcheca"},
    {"ano": 2004, "jogador": "Andriy Shevchenko", "pais": "Ucrânia"},
    {"ano": 2005, "jogador": "Ronaldinho", "pais": "Brasil"},
    {"ano": 2006, "jogador": "Fabio Cannavaro", "pais": "Itália"},
    {"ano": 2007, "jogador": "Kaká", "pais": "Brasil"},
    {"ano": 2008, "jogador": "Cristiano Ronaldo", "pais": "Portugal"},
    {"ano": 2009, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2010, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2011, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2012, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2013, "jogador": "Cristiano Ronaldo", "pais": "Portugal"},
    {"ano": 2014, "jogador": "Cristiano Ronaldo", "pais": "Portugal"},
    {"ano": 2015, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2016, "jogador": "Cristiano Ronaldo", "pais": "Portugal"},
    {"ano": 2017, "jogador": "Cristiano Ronaldo", "pais": "Portugal"},
    {"ano": 2018, "jogador": "Luka Modrić", "pais": "Croácia"},
    {"ano": 2019, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2020, "jogador": "Não houve premiação", "pais": "-"},
    {"ano": 2021, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2022, "jogador": "Karim Benzema", "pais": "França"},
    {"ano": 2023, "jogador": "Lionel Messi", "pais": "Argentina"},
    {"ano": 2024, "jogador": "Rodri", "pais": "Espanha"},
    {"ano": 2025, "jogador": "Ousmane Dembélé", "pais": "França"}
]

df = pd.DataFrame(vencedores)
print(df)

     ano                 jogador               pais
0   1956        Stanley Matthews         Inglaterra
1   1957      Alfredo Di Stéfano  Argentina/Espanha
2   1958            Raymond Kopa             França
3   1959      Alfredo Di Stéfano  Argentina/Espanha
4   1960  Luis Suárez Miramontes            Espanha
..   ...                     ...                ...
65  2021            Lionel Messi          Argentina
66  2022           Karim Benzema             França
67  2023            Lionel Messi          Argentina
68  2024                   Rodri            Espanha
69  2025         Ousmane Dembélé             França

[70 rows x 3 columns]

In [80]:
df = pd.DataFrame(vencedores)
df[df["jogador"] == "Cristiano Ronaldo" ]

     ano            jogador      pais
52  2008  Cristiano Ronaldo  Portugal
57  2013  Cristiano Ronaldo  Portugal
58  2014  Cristiano Ronaldo  Portugal
60  2016  Cristiano Ronaldo  Portugal
61  2017  Cristiano Ronaldo  Portugal

In [5]:
df = pd.DataFrame(vencedores)
df[df["jogador"] == "Lionel Messi" ]

     ano       jogador       pais
53  2009  Lionel Messi  Argentina
54  2010  Lionel Messi  Argentina
55  2011  Lionel Messi  Argentina
56  2012  Lionel Messi  Argentina
59  2015  Lionel Messi  Argentina
63  2019  Lionel Messi  Argentina
65  2021  Lionel Messi  Argentina
67  2023  Lionel Messi  Argentina

In [6]:
df = pd.DataFrame(vencedores)
df[df["ano"] > 2000 ]

     ano              jogador              pais
45  2001         Michael Owen        Inglaterra
46  2002              Ronaldo            Brasil
47  2003         Pavel Nedvěd  República Tcheca
48  2004    Andriy Shevchenko           Ucrânia
49  2005           Ronaldinho            Brasil
50  2006      Fabio Cannavaro            Itália
51  2007                 Kaká            Brasil
52  2008    Cristiano Ronaldo          Portugal
53  2009         Lionel Messi         Argentina
54  2010         Lionel Messi         Argentina
55  2011         Lionel Messi         Argentina
56  2012         Lionel Messi         Argentina
57  2013    Cristiano Ronaldo          Portugal
58  2014    Cristiano Ronaldo          Portugal
59  2015         Lionel Messi         Argentina
60  2016    Cristiano Ronaldo          Portugal
61  2017    Cristiano Ronaldo          Portugal
62  2018          Luka Modrić           Croácia
63  2019         Lionel Messi         Argentina
64  2020  Não houve premiação                 -
65  2021         Lionel Messi         Argentina
66  2022        Karim Benzema            França
67  2023         Lionel Messi         Argentina
68  2024                Rodri           Espanha
69  2025      Ousmane Dembélé            França